zeabur/cli

internal/cmd/service/deploy/deploy.go
pkg/api/interface.go
pkg/api/service.go
pkg/model/service.go

Deprecated marketplace services, use prebuilt services instead.

feat: deploy prebuilt services

---

.gitignore
internal/cmd/context/set/set.go
internal/cmd/deploy/deploy.go
pkg/fill/fill.go
pkg/selector/selector.go

This pull request fixes `zeabur deploy` auto select service bug.  **This pull request is the base of #81**
- Add zeabur.zip into gitignore
- Fixed the bug that when selecting a service with only one service, this service was automatically selected and no create new service option was offered

fix(selector/service): Fix cli deploy auto select service

---

internal/util/pack.go
pkg/api/service.go

This pull request fixes `zeabur deploy` upload error and multiple improvements. **This pull request should be merged after #80 solved**
Issues:
- `zeabur deploy` upload multipart file's size is 0B
- `zeabur deploy` upload has no timeout restriction and lack of closing multipartWriter.
- `zeabur deploy` upload doesn't use `http.NewRequestWithContext` to utilize lifecycle of context
- `zeabur deploy` upload has no error handle after receiving request
-  PackZipFile function still depends on external command `zip` to generate file
-  PackGitRepo function lacks of removing zeabur.zip asset after uploading
Solutions:
- Implement return byte stream of archive file in PackGitRepo function
- Add http client timeout restrict in `http.Client` in UploadZipToService function
- Add defer closure in …

fix(util/pack): Fix code upload deploy zip error

---

go.mod
go.sum
internal/util/pack.go

This issue fixes upload zip's size is 0 byte due to not closing zipWriter.
- Use [klauspost/compress](https://github.com/klauspost/compress?tab=readme-ov-file) to provide best compress performance.
- Closes ZEA-2560

fix(util/pack): Fix pack zip return 0 byte due to not closing zipWriter

---

internal/cmd/root/root.go

This issue fixes token expiry check unusual error.
- Move checkUpdate logic after command excute
- Closes ZEA-2579 

fix(cmd/root): Fix CLI token expiry check

---

internal/cmd/project/create/create.go
pkg/selector/selector.go

This PR changes the displayed message for selecting region when creating services:
before:
after:
the name pattern of region takes references from what shown on AWS console:
- Closes #

chore: change the selection prompt for selecting reigon

---

internal/cmd/completion/completion.go

This PR fix the completion command for `zeabur`.
when generating completion, cobra would take the `Name()` method for the command, which would be the first word in the `Usage` field:
so in this case, the `Usage` field should be the full command of the usage, and start with `zeabur`.
otherwise, the generated completion script would confused with the command:
completion script which is not expected:
completion script which is expected:
- Closes #

fix: fix zeabur commandline completion

---

internal/util/pack.go

- feat(pack): Allow omitting .gitignore file
- fix(pack): Don't print if is os.ErrNotExist
- Closes ZEA-2722

ZEA-2722: allow omitting gitignore file

---

pkg/api/service.go

`createGenericService` has been deprecated. We migrate to the new `createPrebuiltService`.
- Closes ZEA-3037

refactor(api/service): Migrates to createPrebuiltService

---

internal/cmd/template/deploy/deploy.go
pkg/api/interface.go
pkg/api/template.go
pkg/fill/fill.go
pkg/selector/selector.go

For developers, `DeployTemplate` requires `ProjectID` now (you can create a project with `f.ParamFilter.Project`).
For users, you can create (or reuse) a project by the interactive UI or CLI argument, `--project-id`.
- Closes ZEA-3258

feat(api/template): Passing projectID to DeployTemplate

---

pkg/api/interface.go
pkg/api/service.go
pkg/model/service.go

Add `Client` function `CreateCustomService` to create custom image service
- Closes #

feat: add Client function to create custom image service

---

.github/workflows/build-test.yml
.github/workflows/lint.yml
.github/workflows/release.yml

We have upgraded to Go toolchain to 1.21 recently. Besides, the dependency of #101 requires Go 1.22. Therefore, I bump to Go toolchain from 1.20 to 1.22.
- Fix #101 CI

chore: Upgrade CI to Go 1.22

---

.github/workflows/lint.yml

- Upgrade golangci-lint versions.
- Download the dependencies before running `golangci-lint` (sometimes `golangci-lint` does not fetch the dependencies completely)
- Fix CI https://github.com/zeabur/cli/actions/runs/10194941447/job/28202582322 

fix(ci): Upgrade golangci-lint CI

---

go.mod
go.sum
internal/cmd/variable/env/env.go
internal/cmd/variable/variable.go

Add a new command: `variable env`
```
$ zeabur variable env --help
overwrite variables from a .env file
Usage:
zeabur variable env [flags]
Flags:
--env-id string   Environment ID of service
-f, --file string     Path to the .env file (default ".env")
-h, --help            help for env
--id string       Service ID
-n, --name string     Service name
Global Flags:
--auto_check_update    automatically check update (default true)
--auto_refresh_token   automatically refresh token when it's expired, only works when the token is from browser(OAuth2) (default true)
--debug                Enable debug logging
-i, --interactive          use interactive mode (default true)
```
The service variables are overridden with the content of the provided `.env` file.
- Closes ZEA-3754 …

feat(variable): Allow updating variables from .env file

---

pkg/fill/fill.go
pkg/selector/selector.go

Some functions do not handle the `service == nil` case, introducing a nil-pointer panic. This PR fixes it by letting users re-select the project.
`service == nil` is also documented now.
- Closes ZEA-3791

ZEA-3791: nil pointer issue in zeabur/cli

---

internal/util/pack.go

In Windows, pack to ZIP with wrong separator "/" instead of "\\".

Update pack.go for Windows CLI, filepath separator issue

---

internal/util/pack.go

Turns all the `src\app\filename` to `src/app/filename`.
- Closes ZEA-4045
- Suggested label: `bug`

fix(util): Call ToSlash for Windows filename

---

internal/util/pack.go

Reverts #110. Internally we accept only filepath composed with `/`.
- Closes ZEA-4046
- Suggested label: `bug`

fix(util): Do not use filepath.Separator in the zip file

---

internal/cmd/deploy/deploy.go
pkg/model/service.go

Add arguments for deploying automatically:
```
$ zeabur deploy --service-id <service-id> --environment-id <environment-id>
Service deployed successfully, you can access it via:
https://dash.zeabur.com/projects/<project-id>/services/<service-id>?envID=<environment-id>
```
- Closes SUP-560

feat(deploy): Allow specifying service ID and environment ID

---

pkg/api/service.go
pkg/constant/const.go

Use `api.zeabur.com`. `gateway.zeabur.com` is migrating and some stuff (for example, API token) are not working.
- **fix(api): Use ZeaburServerURL constant**
- **feat(constant): Switch to new API endpoint**
- Quick workaround of SUP-1430

Switch to new api.zeabur.com

---

pkg/api/service.go

Migrate to new upload API.
- Closes ZEA-4756

refactor(api): Use new upload API

---

internal/cmd/deploy/deploy.go

Get default environment if environment ID is unspecified, so users don't need to specify `environment-id` manually:
```
npx zeabur@latest deploy --service-id <service-id>
```
- Closes ZEA-4903

feat: get default environment if environmentID is unspecified

---

internal/cmd/template/deploy/deploy.go

This PR enhances error logging for template deployment by adding the "description" field from GraphQL errors when available. Previously, users would only see a generic error message without specific details about what was wrong with their template (this was super confusing - I personally thought there was something wrong with my account, not my template!) Now, the error output includes the detailed description that helps developers quickly identify and fix issues in their templates.
**For example**
Before:
```
$ bunx zeabur@latest template deploy -f zeabur-template.yaml
ERROR   Invalid input (code: INVALID_ARGUMENT)
```
Now:
```
$ bunx zeabur@latest template deploy -f zeabur-template.yaml
ERROR   Invalid input (code: INVALID_ARGUMENT)
Description: Invalid service spec: healthCheck, cause: …
```

fix: enhance error logging for template deploy
